import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="headerFooter">
          <div>
            <h6 className="design-name" style={{ marginLeft: "1.5rem" }}>
              Design by Hussein Salman
            </h6>
          </div>
          <div
            style={{
              display: "flex",
              alignItems: "start",
              justifyContent: "start",
              marginLeft: "1rem",
            }}
          ></div>

          <div className="purchase-path">
            <div className="purchase-step">
              <img
                src="/imgs/location.png"
                className="image-path"
                alt="Post Code"
              />
              <h5>Post Code</h5>
            </div>

            <img src="/imgs/line.png" alt="Waste Type" />
            <div className="purchase-step">
              <img
                src="/imgs/waste.png"
                className="image-path"
                alt="Waste Type"
              />
              <h5>Waste Type</h5>
            </div>
            <img src="/imgs/line.png" alt="Waste Type" />
            <div className="purchase-step">
              <img
                src="/imgs/select.png"
                className="image-path"
                alt="Select Skip"
              />
              <h5>Select Skip</h5>
            </div>
            <img src="/imgs/line.png" alt="Waste Type" />
            <div className="purchase-step">
              <img
                src="/imgs/check.png"
                className="image-path"
                alt="Permit Check"
              />
              <h5>Permit Check</h5>
            </div>
            <img src="/imgs/line.png" alt="Waste Type" />
            <div className="purchase-step">
              <img
                src="/imgs/date.png"
                className="image-path"
                alt="Choose Date"
              />
              <h5>Choose Date</h5>
            </div>

            <img src="/imgs/line.png" alt="Waste Type" />
            <div className="purchase-step">
              <img
                src="/imgs/payment.png"
                className="image-path"
                alt="Payment"
              />
              <h5>Payment</h5>
            </div>
          </div>
        </header>
        {children}

        <footer className="headerFooter">
          <div className="container mx-auto px-4 py-8">
            <p>© {new Date().getFullYear()} REMWaste All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
